# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2da2b831cd4fcff4de0d29a0b5942492f6dae37167bfb22f3fe0f4a687b9ced015a11fdd161b26f400eaa92481e8bcdbb43f3329f8cfecc7897a066bb66a993

test:
  secret_key_base: a7296ac5f72534e393060afb0a9ce335342492d67d40244e3649ad5b8b3dcfa6393e3581a5d4a49440c45e48df7fb7e751435e185f55199ce8550abefab7cb91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
